version: "2017-09-20"

SERVICE_NAME: &SERVICE_NAME 'ai-knowledge-assistant'

shared_vars: &SHARED_ENV
  APPLICATION_ID: *SERVICE_NAME
  COMPONENT_ID: *SERVICE_NAME
  COMPONENT_VERSION: "#{CDP_PULL_REQUEST_AUTHOR}"
  TEAM_ID: "pacman"
  NAMESPACE: "inbound"
  BACKEND_IMAGE: &BACKEND_IMAGE "pacman/zeos-rag-backend:#{CDP_BUILD_VERSION}"
  FRONTEND_IMAGE: &FRONTEND_IMAGE "pacman/zeos-rag-frontend:#{CDP_BUILD_VERSION}"
  STACK_VERSION: "#{CDP_BUILD_VERSION}"
  SCALED_DOWN_STACKS_TO_KEEP: "1"
  MIN_REPLICAS: "1"
  MAX_REPLICAS: "1"
  DB_CPU_REQUEST: 100m
  DB_CPU_LIMIT: 500m
  DB_MEMORY_REQUEST: 512Mi
  DB_MEMORY_LIMIT: 2Gi
  DB_SIZE: "10Gi"
  DB_NAME: "spring_ai_rag_dev"
  DATABASE_ID: "zeos-rag"

stg_vars: &STG_ENV
  CLUSTER_ID: "zfs-test"
  ENVIRONMENT: "staging"
  SCALED_DOWN_STACKS_TTL: "600"
  MIN_REPLICAS: "1"
  REPLICAS: "1"
  BACKEND_CPU_REQUEST: "300m"
  BACKEND_MEMORY_REQUEST: "1.5Gi"
  FRONTEND_CPU_REQUEST: "150m"
  FRONTEND_MEMORY_REQUEST: "768Mi"
  SPRING_PROFILE: "staging"
  JANITOR_TTL: "forever"


allow_concurrent_steps: true
allow_concurrent_pipelines: true

pipeline:
  - id: build
    depends_on: []
    type: script
    vm_config:
      type: linux
      image: cdp-runtime/jdk21
    env:
      <<: *SHARED_ENV
      CODACY_API_BASE_URL: "https://codacy.bus.zalan.do"
    commands:
      - desc: "Run backend tests"
        cmd: |
          cd backend
          ./gradlew test
          ./gradlew build
      - desc: "Build and push backend Docker image"
        cmd: |
          cd backend

          FULL_BACKEND_IMAGE=$CDP_REGISTRY/${BACKEND_IMAGE}
          docker build -t ${FULL_BACKEND_IMAGE} .
          docker push ${FULL_BACKEND_IMAGE}
          cdp-promote-image ${FULL_BACKEND_IMAGE}
      - desc: "Build and push frontend Docker image"
        cmd: |
          cd frontend
          FULL_FRONTEND_IMAGE=$CDP_REGISTRY/${FRONTEND_IMAGE}
          echo "Build frontend docker image: ${FULL_FRONTEND_IMAGE}"
          docker build -t ${FULL_FRONTEND_IMAGE} .
          docker push ${FULL_FRONTEND_IMAGE}
          cdp-promote-image ${FULL_FRONTEND_IMAGE}


  - id: deploy-staging
    desc: 'Deploy staging'
    depends_on:
      - build
    when:
      branch: main
      event: push
    type: deploy
    target: "zfs-test"
    sources:
      - dir: deploy/apply
        default_namespace: "inbound"
        template_vars:
          <<: [ *STG_ENV, *SHARED_ENV ]
          AWS_SECRET_ACCESS_KEY: "deployment-secret:2:zfs-test:AQICAHio/xEglCgY3R9ACIULrXtH8Ip/opvy59+Ua8gcImGzPgGzrZ4KDzhABy/28tMDugSbAAAA5zCB5AYJKoZIhvcNAQcGoIHWMIHTAgEAMIHNBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDB+VD5C5NIHYtffv5AIBEICBn+BN5IAQ3FI1rcgm1OzOLOTvpSxEB+F85hWZNsYUi2zo+LKI2N9SFfBN6Sq8KOOYllnboNuKBUDWr3eQwNMczY64gRAX0uSKLuNqPSXEupdkRrqtZ8wG7muOhFKceWIf1qMFqGWUlHPMNpFgb3fGagXdw9yrg2zkGDH4hx7T8CaWcXhP7VtbsT/8uzmUfsDEdl94bEBcNtKgejsm7v2LgA=="
          AWS_ACCESS_KEY_ID: "BedrockAPIKey-1txo-at-752508157939"
  - id: traffic-stg-backend
    type: traffic
    when:
      branch: main
      event: push
    depends_on:
      - deploy-staging
    target: "zfs-test"
    namespace: "inbound"
    stackset: "zeos-rag-backend-staging"
    stack_version: "#{CDP_BUILD_VERSION}"
    target_percentage: 100
    requires_human_approval: false

  - id: traffic-stg-frontend
    type: traffic
    when:
      branch: main
      event: push
    depends_on:
      - deploy-staging
    target: "zfs-test"
    namespace: "inbound"
    stackset: "zeos-rag-frontend-staging"
    stack_version: "#{CDP_BUILD_VERSION}"
    target_percentage: 100
    requires_human_approval: false
