apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeos-rag-backend-service-account
  namespace: "{{{NAMESPACE}}}"
  annotations:
    iam.amazonaws.com/role: "{{{APPLICATION_ID}}}-{{{ENVIRONMENT}}}-iam-role"
